spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://auth.kimleang.space/auth/realms/rest-api
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
eureka:
  client:
    service-url:
      defaultZone: http://34.126.135.232:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 34.126.135.232
server:
  port: 8081
  ssl:
    enabled: false
keycloak:
  server-url: https://auth.kimleang.space/auth
  realm: rest-api
  client-id: oauth-admin-client
  client-secret: RZtPb3KBuX8j3LHTyYMnmT1L95MJctLN
minio:
  url: http://34.126.135.232:9000
  access-name: admin
  access-secret: admin123
  bucket-name: mini-project

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info
