spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/rest-api
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081
  ssl:
    enabled: false
keycloak:
  server-url: http://localhost:8080
  realm: rest-api
  client-id: oauth-admin-client
  client-secret: dY90Uo2nz8UGAZ1fdGAEloOf8rK16cIo
minio:
  url: http://localhost:9000
  access-name: admin
  access-secret: admin123
  bucket-name: mini-project

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info
