spring:
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    datasource:
        url: jdbc:postgresql://34.124.146.39:5432/mini-project
        username: group03
        password: 123
    security:
     oauth2:
         resourceserver:
             jwt:
                 issuer-uri: https://auth.kimleang.space/auth/realms/my-realm
eureka:
    client:
        service-url:
            defaultZone: http://34.124.146.39:8761/eureka/

    instance:
        prefer-ip-address: true
        ip-address: 34.124.146.39
        
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
