spring:
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    datasource:
        url: jdbc:postgresql://34.126.135.232:5434/userdb
        username: postgres
        password: 123
    security:
     oauth2:
         resourceserver:
             jwt:
                 issuer-uri: https://auth.kimleang.space/auth/realms/rest-api

eureka:
    client:
        service-url:
            defaultZone: http://34.126.135.232:8761/eureka/

        
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info
