spring : 
  security:
  oauth2:
    resource-server:
      jwt:
        issuer-uri: http://localhost:8080/realms/rest-api
datasource:
  username: group03
  password: 123
  url: jdbc:postgresql://34.124.146.39:5432/products
jpa:
  hibernate:
    ddl-auto: update

eureka:
client:
  service-url:
    defaultZone: http://localhost:8761/eureka/
