spring: 
  security:
  oauth2:
    resource-server:
      jwt:
        issuer-uri: https://auth.kimleang.space/auth/realms/rest-api

datasource:
  username: postgres
  password: 1234
  url: jdbc:postgresql://localhost:5432/productdb
jpa:
  hibernate:
    ddl-auto: update

eureka:
client:
  service-url:
    defaultZone: http://34.126.135.232:8761/eureka/
