spring: 
  security:
  oauth2:
    resource-server:
      jwt:
        issuer-uri: https://auth.kimleang.space/auth/realms/rest-api

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    datasource:
        url: jdbc:postgresql://localhost:5433/userdb
        username: postgres
        password: 123

eureka:
client:
  service-url:
    defaultZone: http://34.126.135.232:8761/eureka/
