spring:
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    datasource:
        url: jdbc:postgresql://34.126.135.232:5433/userdb
        username: postgres
        password: 123
    security:
     oauth2:
         resourceserver:
             jwt:
                 issuer-uri: https://auth.kimleang.space/auth/realms/rest-api

eureka:
    client:
        service-url:
            defaultZone: http://34.126.135.232:8761/eureka/

        
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info

  zipkin:
    tracing:
      endpoint: http://34.126.135.232:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
      
springdoc:
  api-docs:
    path: /v3/api-docs
